name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  style:
    name: "Style check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pyflakes black isort codespell
      - name: Run PyFlakes
        run: |
          pyflakes .
      - name: Run black
        run: |
          black --check $(git ls-files '*.py')
      - name: Run isort
        run: |
          isort --check --profile black $(git ls-files '*.py')
      - name: Run spell-check
        run: |
          codespell $(git ls-files)
